language: c

env:
    - SMVERSION=1.5
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib wget

before_script:
    - SMPACKAGE=`wget -qO- http://nikkii.us/smlink.php?ver=$SMVERSION&platform=linux`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp -R scripting/* addons/sourcemod/scripting/
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh `ls ../../../scripting | grep sp`

after_script:
    - ls compiled